name: cuML wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'
  workflow_call:
    inputs:
      versioneer-override:
        type: string
        default: ''
      build-tag:
        type: string
        default: ''
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build-type:
        type: string
        default: nightly

concurrency:
  group: "cuml-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cuml-wheel:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@main
    with:
      repo: rapidsai/cuml

      build-type: ${{ inputs.build-type || 'pull-request' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}

      package-dir: python
      package-name: cuml

      python-package-versioneer-override: ${{ inputs.versioneer-override }}
      python-package-build-tag: ${{ inputs.build-tag }}

      skbuild-configure-options: "--log-level=DEBUG -DCUML_RAFT_REPOSITORY=https://github.com/vyasr/raft.git -DCUML_RAFT_BRANCH=feat/cibuildwheel -DCPM_DOWNLOAD_ALL=ON -DCUML_BUILD_WHEELS=ON -DDETECT_CONDA_ENV=OFF -DDISABLE_FORCE_CLONE_RAFT=ON"

      # Need to install CMake because treelite needs to be compiled for arm (no wheels available).
      # TODO: Need to install distributed from the main branch because our
      # dask-cuda contains very new changes, but this installation probably
      # shouldn't stick and should be removed once we pin versions
      # appropriately
      test-before-amd64: "pip install git+https://github.com/dask/distributed.git@main"
      test-before-arm64: "pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64 && pip install cmake && pip install git+https://github.com/dask/distributed.git@main"
      test-extras:  "test"
      test-unittest: "pytest -v ./python/cuml/tests"
    secrets: inherit
